spring:
  config:
    activate:
      on-profile: ${ACTIVE_PROFILE}

  application:
    name: sign-up

  datasource:
    url: ${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/signup_db}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_SMTP_USERNAME}
    password: ${GOOGLE_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    key: ${JWT_SECRET}
    expiration:
      access : ${JWT_ACCESS_EXPIRATION_SECOND}
      refresh: ${JWT_REFRESH_EXPIRATION_SECOND}
      invite: ${JWT_INVITE_EXPIRATION_SECOND}
      validate: ${JWT_VALIDATE_EMAIL_EXPIRATION_SECOND}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

#  rabbitmq:
#    host: ${RABBIT_MQ:localhost}
#    username: ${RABBIT_USERNAME:guest}
#    password: ${RABBIT_PASSWORD:guest}
#    port: 5672
#    listener:
#      simple:
#        prefetch: 1
#        concurrency: 25
#        max-concurrency: 25
#        retry:
#          enabled: true
#          initial-interval: 2s
#          max-interval: 10s
#          max-retries: 5
#          multiplier: 2


frontend:
  url: ${FRONTEND_URL}

auth:
  refresh-cookie:
    name: refreshToken
    http-only: true
    secure: ${REFRESH_COOKIE_SECURE:true}
    same-site: ${REFRESH_COOKIE_SAME_SITE:None}
    path: /auth


