spring:
  application:
    name: sign-up

  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_SMTP_USERNAME}
    password: ${GOOGLE_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    key: ${JWT_SECRET}
    expiration:
      access : ${JWT_ACCESS_EXPIRATION_SECOND}
      refresh: ${JWT_REFRESH_EXPIRATION_SECOND}
