### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "gooch123@naver.com",
  "password": "1234"
}

### 액세스 토큰 검증
GET localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJleHAiOjE3NzcxNTAyNzIsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6Imdvb2NoMTIzQG5hdmVyLmNvbSJ9.VB8L-4zH5OxkrK3I8XG2qoe2lyRMg8URovbtacsuZpYpmkV8DCXmG-N0P3ciC53k

### 새 유저 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "gooch123@naver.com",
  "password": "12341234",
  "username": "gooch123"
}

### 새 유저 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "12341234"
}

### 리프레쉬 토큰 인증
POST localhost:8080/auth/refresh

### 로그아웃
POST localhost:8080/auth/logout
