### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "12341234"
}

### 액세스 토큰 검증
GET localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg2NjcwNjYsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6InRlc3RAZW1haWwuY29tIn0.epNPvA6ewvwBiWv_496Mh6i3gk9N7oTEXEnDSa8_CfoH2H7n73d7lSzOUUqOXz5CA3Z8q8w8frgYBoj9-q63UQ

### 새 유저 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "gooch@naver.com",
  "password": "12341234",
  "nickname": "gooch123"
}

### 새 유저 로그인
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "gooch123@naver.com",
  "password": "12341234"
}

### 리프레쉬 토큰 인증
POST localhost:8080/auth/refresh

### 로그아웃
POST localhost:8080/auth/logout

### 이메일 인증 요청
POST localhost:8080/auth/email/request
Content-Type: application/json

{
  "email": "gooch@naver.com"
}

### 이메일 인증
POST localhost:8080/auth/email/validate
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg2NDg5NzMsInN1YiI6ImVtYWlsX3ZhbGlkYXRlX3Rva2VuIiwidmFsaWRhdGVfZW1haWwiOiJnb29jaEBuYXZlci5jb20ifQ.TyYzgcbgyPXiEvGp7zH2aeVTRmEfixs-2TqK94e9QDqf0KwgT4MZE5b5G4Fs0S4kzvBlRhh6i_fb3-laMhL4KQ"
}
