### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 워크스페이스 초대
POST http://localhost:8080/workspace/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg2Nzg3OTUsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6InRlc3RAZW1haWwuY29tIn0.X5nJdLdiltaLWgJSIKQB1pPAk7saWCx57QalcCRXjMmJvIHdf2-hG0cMjAOq97pPMOvbpLmwoxvfctFVXIbp5g

{
  "workspaceId" : 1,
  "toEmailList": ["gooc@naver.com"]
}


### 초대 수락
POST http://localhost:8080/workspace/invite/accept
Content-Type: application/json

{
  "inviteToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg4MjMzNTcsInN1YiI6IndvcmtzcGFjZV9pbnZpdGVfdG9rZW4iLCJ0b19lbWFpbCI6Imdvb2NAbmF2ZXIuY29tIiwiZnJvbV9lbWFpbCI6InRlc3RAZW1haWwuY29tIiwid29ya3NwYWNlX3VybCI6ImR1bW15IHVybDEifQ.XTAid1WssbDF9FTz6BaGZl4c01oJR5dXwQo-WrW1XKM6HUihtjhnt_Jvq-dE_1jVru-4jxyEtb5_2Xz6Wyb33g"
}
