### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 워크스페이스 초대
POST http://localhost:8080/workspace/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzcxNDIzMTIsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6Imdvb2NoMTIzQG5hdmVyLmNvbSJ9.eHlLEgr93NT21fa42ZkTVpPD70Q4re7laUqG82_rRNk

{
  "workspaceId" : 1,
  "toEmail": "gooch123@naver.com"
}

### 초대 수락
POST http://localhost:8080/workspace/invite/accept
Content-Type: application/json

{
  "inviteToken": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NzcyODU4NzgsInN1YiI6IndvcmtzcGFjZV9pbnZpdGVfdG9rZW4iLCJ0b19lbWFpbCI6Imdvb2NoMTIzQG5hdmVyLmNvbSIsImZyb21fZW1haWwiOiJnb29jaDEyM0BuYXZlci5jb20iLCJ3b3Jrc3BhY2VfdXJsIjoiZHVtbXkgdXJsIn0.ptjCTDe1T74rNrFWPifMh98yhuJso9YJFYK7RCeJWRU"
}
