### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 워크스페이스 초대
POST http://localhost:8080/workspace/invite
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "workspaceId" : 4,
  "toEmailList": ["gooc@naver.com"]
}


### 초대 수락
POST http://localhost:8080/workspace/invite/accept
Content-Type: application/json

{
  "inviteToken": "eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3NzkwMDY5OTYsInN1YiI6IndvcmtzcGFjZV9pbnZpdGVfdG9rZW4iLCJ0b19lbWFpbCI6Imdvb2NAbmF2ZXIuY29tIiwiZnJvbV9lbWFpbCI6InRlc3RAZW1haWwuY29tIiwid29ya3NwYWNlX3VybCI6ImR1bW15IHVybDQifQ.pEfFtDHs_oKmGuaJFunWqxoaj-a0BN2GVhRMfhD1xPDBEI-3krDx0_XA2-Sn4a7ioMzZlOtJRbal6CE7va8LUA"
}
