### 워크스페이스 삭제
DELETE localhost:8080/workspace/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg4NTUyNTUsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6InRlc3RAZW1haWwuY29tIn0.Dk09b0f1oN0ieQ9ixhfJauFGE5GJpBxXPuyiIf-tYU3rhd8iQ2AQva9EBHT4XhtCmBP42xsaqlBVE8uyzkRISQ

### 워크스페이스 조회
GET localhost:8080/workspace/my
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg4NTUyNTUsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6InRlc3RAZW1haWwuY29tIn0.Dk09b0f1oN0ieQ9ixhfJauFGE5GJpBxXPuyiIf-tYU3rhd8iQ2AQva9EBHT4XhtCmBP42xsaqlBVE8uyzkRISQ

### 워크스페이스 멤버 조회
GET localhost:8080/workspace/1/members
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE3Nzg4NTUyNTUsInN1YiI6ImFjY2Vzc190b2tlbiIsIm1lbWJlcl9lbWFpbCI6InRlc3RAZW1haWwuY29tIn0.Dk09b0f1oN0ieQ9ixhfJauFGE5GJpBxXPuyiIf-tYU3rhd8iQ2AQva9EBHT4XhtCmBP42xsaqlBVE8uyzkRISQ
